name = "LOWDER"
uuid = "d509e0f1-0006-4f92-afa6-b6c7a94d868b"
authors = ["Anderson Schwertner <andersonschwertner@hotmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
